export { createLogicEngine } from "./engine";
export { adaptLegacyRule } from "./adapters";
export type {
  EngineDefinition,
  EngineOptions,
  EngineRule,
  EvalContext,
  EvalResult,
  EvalResultType,
  EvalResultNextStep,
  EvalResultEnding,
  EvalResultRedirect,
  EvalResultScheduling,
  EvalResultCompute,
  EvalResultSetVariable,
  EvalResultWebhook,
  EvalResultCrmAction,
  EvalResultComplete,
  EvalResultContinue,
  EvalResultError,
  LogicEngine,
  ConditionOperator,
  ConditionGroup,
  ConditionNode,
  LeafCondition,
  ConditionValue,
  RuleAction,
  StepDefinition,
  EndingDefinition,
  DecisionTrace,
  ExplainEntry,
  LeafEvalTrace,
  EvalExplanation,
  ValidationError,
  EngineErrorCode,
  OperatorFn,
  SessionContext,
  LeadContext,
  UtmContext,
  ContextSource,
} from "./types";
