"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { toast } from "sonner";
import type { MarketingAsset, MarketingContent, MarketingContentInput, MarketingIdea, MarketingIdeaInput, MarketingMember } from "@/types/marketing";

interface Value {
  contents: MarketingContent[]; ideas: MarketingIdea[]; assets: MarketingAsset[]; members: MarketingMember[]; isAdmin: boolean; isLoading: boolean; error: string | null; refetch: () => Promise<void>;
  createContent: (input: MarketingContentInput) => Promise<MarketingContent | null>; updateContent: (id: string, input: MarketingContentInput) => Promise<boolean>; archiveContent: (id: string) => Promise<boolean>;
  createIdea: (input: MarketingIdeaInput) => Promise<MarketingIdea | null>; updateIdea: (id: string, input: MarketingIdeaInput) => Promise<boolean>; planIdea: (id: string, input: MarketingContentInput) => Promise<MarketingContent | null>; archiveIdea: (id: string) => Promise<boolean>;
  uploadAsset: (file: File, category: string) => Promise<MarketingAsset | null>; updateAsset: (id: string, input: { name: string; category: string; tags?: string[] }) => Promise<boolean>; archiveAsset: (id: string) => Promise<boolean>;
}
const Context = createContext<Value | null>(null);
async function request<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init); const json = await response.json().catch(() => ({})) as T & { error?: string }; if (!response.ok) throw new Error(json.error ?? "Não foi possível concluir a operação"); return json; }

export function MarketingProvider({ children }: { children: ReactNode }) {
  const [contents, setContents] = useState<MarketingContent[]>([]); const [ideas, setIdeas] = useState<MarketingIdea[]>([]); const [assets, setAssets] = useState<MarketingAsset[]>([]); const [members, setMembers] = useState<MarketingMember[]>([]); const [isAdmin, setIsAdmin] = useState(false); const [isLoading, setIsLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const refetch = useCallback(async () => { try { setError(null); const data = await request<{ contents: MarketingContent[]; ideas: MarketingIdea[]; assets: MarketingAsset[]; members: MarketingMember[]; is_admin: boolean }>("/api/marketing"); setContents(data.contents); setIdeas(data.ideas); setAssets(data.assets); setMembers(data.members); setIsAdmin(data.is_admin); } catch (err) { setError(err instanceof Error ? err.message : "Erro ao carregar Marketing"); } finally { setIsLoading(false); } }, []);
  useEffect(() => { void refetch(); }, [refetch]);
  const createContent = useCallback(async (input: MarketingContentInput) => { try { const data = await request<{ content: MarketingContent }>("/api/marketing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource: "contents", ...input }) }); await refetch(); toast.success("Conteúdo criado"); return data.content; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao criar conteúdo"); return null; } }, [refetch]);
  const updateContent = useCallback(async (id: string, input: MarketingContentInput) => { const previous = contents; setContents((items) => items.map((item) => item.id === id ? { ...item, ...input } as MarketingContent : item)); try { await request(`/api/marketing/contents/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); await refetch(); toast.success("Conteúdo atualizado"); return true; } catch (err) { setContents(previous); toast.error(err instanceof Error ? err.message : "Erro ao atualizar conteúdo"); return false; } }, [contents, refetch]);
  const archive = useCallback(async (resource: string, id: string) => { try { await request(`/api/marketing/${resource}/${id}`, { method: "DELETE" }); await refetch(); toast.success("Item arquivado"); return true; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao arquivar"); return false; } }, [refetch]);
  const createIdea = useCallback(async (input: MarketingIdeaInput) => { try { const data = await request<{ idea: MarketingIdea }>("/api/marketing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource: "ideas", ...input }) }); await refetch(); toast.success("Ideia adicionada"); return data.idea; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao criar ideia"); return null; } }, [refetch]);
  const updateIdea = useCallback(async (id: string, input: MarketingIdeaInput) => { try { await request(`/api/marketing/ideas/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); await refetch(); toast.success("Ideia atualizada"); return true; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao atualizar ideia"); return false; } }, [refetch]);
  const planIdea = useCallback(async (id: string, input: MarketingContentInput) => { try { const data = await request<{ content: MarketingContent }>(`/api/marketing/ideas/${id}/plan`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); await refetch(); toast.success("Ideia planejada no calendário"); return data.content; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao planejar ideia"); return null; } }, [refetch]);
  const uploadAsset = useCallback(async (file: File, category: string) => { try { const signed = await request<{ signed_url: string; storage_path: string; public_url: string }>("/api/marketing/assets/sign", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ file_name: file.name, mime_type: file.type, file_size: file.size }) }); const upload = await fetch(signed.signed_url, { method: "PUT", headers: { "Content-Type": file.type }, body: file }); if (!upload.ok) throw new Error("Falha ao enviar arquivo"); const data = await request<{ asset: MarketingAsset }>("/api/marketing", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ resource: "assets", name: file.name, category, mime_type: file.type, file_size: file.size, storage_path: signed.storage_path, public_url: signed.public_url }) }); await refetch(); toast.success("Asset enviado"); return data.asset; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro no upload"); return null; } }, [refetch]);
  const updateAsset = useCallback(async (id: string, input: { name: string; category: string; tags?: string[] }) => { try { await request(`/api/marketing/assets/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(input) }); await refetch(); toast.success("Asset atualizado"); return true; } catch (err) { toast.error(err instanceof Error ? err.message : "Erro ao atualizar asset"); return false; } }, [refetch]);
  const value = useMemo<Value>(() => ({ contents, ideas, assets, members, isAdmin, isLoading, error, refetch, createContent, updateContent, archiveContent: (id) => archive("contents", id), createIdea, updateIdea, planIdea, archiveIdea: (id) => archive("ideas", id), uploadAsset, updateAsset, archiveAsset: (id) => archive("assets", id) }), [contents, ideas, assets, members, isAdmin, isLoading, error, refetch, createContent, updateContent, archive, createIdea, updateIdea, planIdea, uploadAsset, updateAsset]);
  return <Context.Provider value={value}>{children}</Context.Provider>;
}
export function useMarketing() { const value = useContext(Context); if (!value) throw new Error("useMarketing fora do provider"); return value; }
